### ISSUE TITLE
Question / Issue with eth_trie

### ISSUE THREAD

**Issue by jonas089** [HerodotusDev/trie-proofs#20] opened 2024-11-20 15:27 UTC
@

```rust
        let key = load_infura_key_from_env();
        println!("Key: {}", key);
        let rpc_url = "https://mainnet.infura.io/v3/".to_string() + &key;
        let provider = Provider::try_from(rpc_url).expect("Failed to construct provider!");
        // works with
        let block_hash = "0x8230bd00f36e52e68dd4a46bfcddeceacbb689d808327f4c76dbdf8d33d58ca8";
        // does not work with
        // 0xfa2459292cc258e554940516cd4dc12beb058a5640d0c4f865aa106db0354dfa

        let block = provider
            .get_block_with_txs(H256::from_str(block_hash).unwrap())
            .await
            .expect("Failed to get Block!")
            .expect("Block not found!");

        let memdb = Arc::new(MemoryDB::new(true));
        let mut trie = EthTrie::new(memdb.clone());

        for (index, tx) in block.transactions.iter().enumerate() {
            trie.insert(&index.rlp_bytes(), &tx.rlp())
                .expect("Failed to insert");
            println!("index {}: {:?}", index, index.rlp_bytes());
        }

        println!("transaction count: {}", block.transactions.len());

        let transaction_root = block.transactions_root;
        println!(
            "Expected Transaction Root: {:?}",
            &transaction_root.as_bytes()
        );
        let trie_root = trie.root_hash().unwrap();

        println!("Transaction Root raw: {}", &block.transactions_root);
        println!("Transaction Root raw: {}", &trie_root);
        assert_eq!(trie_root.to_vec(), transaction_root.as_bytes());

        /*let tx_index = block
        .transactions
        .iter()
        .position(|tx| tx.hash == H256::from_str(untrusted_hash).unwrap())
        .ok_or("Transaction not found in block")
        .unwrap();*/

        let tx_index = 0u64;
        let tx_key = tx_index.to_be_bytes();
        let proof = trie.get_proof(&tx_key).unwrap();

        println!(
            "Root from Proof: {:?}",
            &digest_keccak(proof.first().unwrap()).bytes()
        )
        // Trie potentially flawed, see https://github.com/ethereum/eth-trie.rs/issues/4
```

I am experiencing some issues with eth_trie and looking at this library I think that you guys might be interested in this issue (or at least will be able to help me understand it better):

https://github.com/ethereum/eth-trie.rs/issues/4

@petscheit @rkdud007

**Comment by petscheit** [comment] 2024-11-20 15:55
Hey mate, thanks for flagging this. Could you tell me what chain this block hash corresponds to? Not able to find it on sepl or mainnet

**Comment by jonas089** [comment] 2024-11-20 16:21
Those are recent blocks, might not have been indexed yet? Got them off the mainnet explorer starting page.

**Comment by KolbyML** [comment] 2024-11-20 18:37
The issue is fixed with https://github.com/ethereum/eth-trie.rs/issues/4 I believe. There wasn't an actual bug, just some confusion with EIP-2718 which honestly tripped me up in the past as well.

**Closed as completed** 2024-11-21 04:03 UTC
